version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:13.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
  pgadmin:
    image: dpage/pgadmin4        
    env_file:
      - ./.env.prod.db
    volumes:
       - pgadmin:/root/.pgadmin
       - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8888:80"
    restart: unless-stopped


volumes:
  postgres_data:
  static_volume:
  pgadmin:
